### ISSUE TITLE
Order status "Submitted" not displayed correctly

### ISSUE THREAD

**Issue by andreaskring** [magenta-aps/E-Ark-Platform-UI#27]
The order status "Submitted" (recently added in the backend) is not displayed correctly in the list of orders in OMT. Instead there is a blue label saying "ORDER.ORDERS.STAT"

**Comment by iamfrank** [comment]
Sounds like a missing translation. I can't debug it, though, because submitting orders seems to be broken.

**Comment by iamfrank** [comment]
Possibly fixed in develop branch due to #30

**Comment by andreaskring** [comment]
@iamfrank Ok - I will pull the latest develop an see if it is working

**Comment by andreaskring** [comment]
This is fixed
