### ISSUE TITLE
Button for updating the (earkweb) status of all submitted orders

### ISSUE THREAD

**Issue by andreaskring** [magenta-aps/E-Ark-Platform-UI#32]
In the OMT: on the page listing all the orders we need a button called (e.g.) "Update status" that updates the status of all orders (this button will make a request to the earkweb querying the statuses of the orders). The HTTP request to be made when clicking the button should be:

`GET /api/earkweb/updateAllOrderStatus`

This will update the DB with the new order statuses (so if the page could be refreshed, the new statuses should be displayed). When making the call above, JSON like this is returned:

```
{
  "message": "Status of the orders are updated in the DB", 
  "ordersUpdatedToDone": [
    "e807ea0b5be3413c9197c2917a02b994"
  ], 
  "success": true
}
```

**Comment by iamfrank** [comment]
This is implemented - at least in feature/ui_modifications
